package koczwara.mundialv1.MVC.Model.enums;

public enum enumGrupy {
    A, B, C, D, E, F, G, H, JEDNA_OSMA_GRUPA_PIERWSZA, JEDNA_OSMA_GRUPA_DRUGA, JEDNA_OSMA_GRUPA_TRZECIA, JEDNA_OSMA_GRUPA_CZWARTA, JEDNA_OSMA_GRUPA_PIATA,
    JEDNA_OSMA_GRUPA_SZOSTA, JEDNA_OSMA_GRUPA_SIODMA, JEDNA_OSMA_GRUPA_OSMA, JEDNA_CZWARTA_GRUPA_PIERWSZA, JEDNA_CZWARTA_GRUPA_DRUGA,JEDNA_CZWARTA_GRUPA_TRZECIA,
    JEDNA_CZWARTA_GRUPA_CZWARTA, JEDNA_DRUGA_GRUPA_PIERWSZA, JEDNA_DRUGA_GRUPA_DRUGA, FINAL_MISTRZOSTW
}
